CREATE TABLE INVENTARIO_IDT (
    ID_EQUIPO SERIAL PRIMARY KEY,
    TIPO_EQUIPO VARCHAR(100) NOT NULL,
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    SERIE VARCHAR(100) UNIQUE,
    ACTIVO VARCHAR(20),
    ESTADO VARCHAR(50),
    CONDICION_EQUIPO VARCHAR(50),
    COMENTARIO VARCHAR(200),
    FECHA_COMPRA DATE NOT NULL,
    FECHA_ASIG DATE,
    FECHA_MANTENIMIENTO DATE,
    USUR_INGRESA VARCHAR(15),
    FOTO_EQUIPO VARCHAR(255),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM INVENTARIO_IDT;